### PR TITLE
submitting the quiz

### PR DESCRIPTION
**Pull request by katspears206**

### CODE REVIEW

**Comment by stevebrownlee** [comment]
@katspears206 Great first attempt. Your HTML structure looks spot on.  As for the CSS, play around with the styling a bit more so that the text sizes matches (as close as possible) what's in the sample image.

**Comment by katspears206** [comment]
Thank you for that. I did want to clarify I should play around with it and resubmit/do a new pull request?

**Comment by JoeShep** [comment]
This quiz needs to be closed out.  Please take care of the last couple of items and let's get you a thumbs-up.

**Comment by katspears206** [comment]
Okie doke I believe I finished making those edits and pushed them

**Comment by JoeShep** [comment]
Look at those happy `<li>` tags all nestled in their `<ul>` parents' arms.  :+1: Merge it!

**Pull request merged**
